############################################################
## Hugo ClearStatus config
############################################################

baseUrl: "https://status.its.lib.k-state.edu"

# Complete page title
title: K-State Libraries Internal Systems Status Page

# Language config
languageCode: en

############################################################
## More default config. in /config/_default/config.yml
############################################################


############################################################
## Status default config. Valid for ALL languages.
############################################################

params:
  systems:
    - name: Alma
    - name: Annex
    - name: Archivematica
    - name: AtoM
      description: Access to Memory - Special Collections
      link: https://findingaids.lib.k-state.edu/
    - name: Executive Court
    - name: EZproxy
      description: Remote Access System
    - name: ILLiad
      description: Interlibrary Loan System
    - name: Joan
      description: Joan Room Scheduling System
    - name: K-REx
      description: Institutional Repository
      link: https://krex.k-state.edu
    - name: New Literacies Alliance LMS
      description: NLA LMS based on Open edX
      link: https://online.newliteraciesalliance.org
    - name: OCLC
      description: Systems that are provided by OCLC will be tagged here as well.
    - name: Phoenix
      description: Library Network Storage
    - name: Redmine
      link: https://it.lib.k-state.edu/projects
      description: Library Ticketing System
    - name: Springshare
      description: LibCal, LibGuides, and other Springy products
    - name: StaffNet
      link: https://staffnet.lib.k-state.edu
    - name: Website
      description: K-State Libraries Website
      link: https://lib.k-state.edu/

  # dateFormat Default: "January 2, 2006 at 3:04 PM"
  # shortDateFormat Default: "15:04 — Jan 2"
  dateFormat: "January 2, 2006 at 3:04 PM"
  shortDateFormat: "15:04 — Jan 2"
  # This string will be displayed after each time displayed
  # Set it for instance to " UTC" to indicate UTC times
  # or a specific time zone, ie " America/New_York"
  # You can also instead used a translated string per language
  timezoneString: " America/Chicago"

  # Path to logo image from the /static folder.
  logo: "/images/clearstatus.svg"

  # favicon
  icon: "/images/clearstatus.png"
  iconType: "image/png"

  # Descriptions
  meta_description: "This status page provides updated information about our systems normal operation, incidents that may happen and their resolution."
  # description_footer: "<a class='text-grey-darkest' title='Visit example.com' href='https://www.example.com/'>Example.com</a> provides open-source software for all kind of sectors."
  # description_header: "Information about <a class='text-grey-darkest' title='Visit example.com' href='https://www.example.com/'>example</a> systems operations.<br />Follow us <a class='text-grey-darkest' title='Visit our page on Twitter' href='https://www.twitter.com/example'>on Twitter</a> or subscribe to <a class='text-grey-darkest' href='%s' >RSS</a><br />to be alerted of new events."

  copyrightHolder: "K-State Libraries"

  # Disqus commenting per issue: set your Disqus shortname here
  # Leave empty for no discussion at all.
  # You can also enable/disable discussions per issue
  disqusShortname:

  # Layout
  eventsPerPage: 10

############################################################
## More default config. in /config/_default/params.yml
############################################################
